language: python

cache:
  - ccache
  - pip

jobs:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7
    - os: linux
      python: 3.8
  allow_failures:
    - os: linux
      python: 2.7
    - os: linux
      python: 3.8

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

install:
  - conda create --name=light-head-rcnn python=$TRAVIS_PYTHON_VERSION -q -y
  - source activate light-head-rcnn 
  - conda install -c menpo opencv
  - pip install Cython
  - pip install 'git+https://github.com/cocodataset/cocoapi.git#egg=pycocotools&subdirectory=PythonAPI'
  - pip install -r requirements.txt
  - pip install -e .

before_script:
  - pip install flake8
  - pip install hacking
  - pip install autopep8
  - pip install mock
  - pip install pytest

script:
  - flake8 .
  - pytest -m "not gpu" tests

notifications:
  email: false
